### ISSUE TITLE
C# Playwright 

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/axe-pipelines-samples#809]
## Is your feature request related to a problem? Please describe.
My team is currently using the C# + Selenium option from [https://github.com/microsoft/axe-pipelines-samples](https://github.com/microsoft/axe-pipelines-samples) to run Accessibility Insights in our ADO build pipeline but would like to convert all our UIA to using C# + Playwright now that Microsoft has an official .NET port for Playwright ([https://github.com/microsoft/playwright-dotnet](https://github.com/microsoft/playwright-dotnet)). 

## Describe the desired outcome
Can an equivalent C# version of the npm @axe-core/playright package be created?

## Additional context
Creating feature request on behalf of user

**Comment by jeffreyrivor** [comment]
Hi, I'm the original asker that sent this via email. Let me describe our current UI automation setup to add more context.

We are testing an ASP.NET Core app following the docs for [Integration tests with customized WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0#customize-webapplicationfactory); this results in an `HttpClient` that allows sending requests and receiving responses in object form (without having an actual Kestrel server open an actual port on the localhost). Using the `Selenium.WebDriver` NuGet package and the [Fetch domain of the Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/), we drive a Chromium-based browser, intercept relevant requests and route them through this `HttpClient` to generate the response to return to the browser. This essentially results in a functional equivalent of navigating a browser to a page in the app, but without needing to deploy the service anywhere. With that setup, we simply use `Selenium.Axe` (a third-party C# wrapper of `axe-core`) to run accessibility scans through `Selenium.WebDriver`.

We have a desire to move from using `Selenium.WebDriver` library to using `Microsoft.Playwright` (the official .NET language port), primarily because the underlying support of the Chrome DevTools Protocol in `Selenium.WebDriver` is tightly coupled to the library and is out-of-date (v96) with current Chromium stable; see SeleniumHQ/selenium#10583 for details. We are only using `Selenium.WebDriver` due to the lack of an `axe-core` .NET language port that works with `Microsoft.Playwright`. With Chromium stable going to version 100+ now, the `Selenium.WebDriver` library no longer works with latest stable because it only allows a gap of up to 4 major versions between the web driver and itself (the newest version in the latest 4.1.0 package is the v96 protocol).

**Comment by dbjorge** [comment]
Just an update on this: our team is currently working with Deque and with the author of https://github.com/IsaacWalker/PlaywrightAxeDotnet to migrate that library to be the basis of a new, officially Deque-supported C# Playwright integration library. Once we've completed that work and gotten the library published, we'll be adding a new sample based on it here (tracked by this issue), as well as official https://playwright.dev documentation similar to the sample (tracked by https://github.com/microsoft/playwright/issues/14112)

**Comment by Gso-1** [comment]
Hola Los Puedo Agregar Y suscribir y darles toda mi asesoría pero tenemos que llegar a un acuerdo de proceso de acuerdo de negocios para que sea el mas optimo para todos

**Comment by Gso-1** [comment]
> ## ¿Su solicitud de función está relacionada con un problema? Sírvase describir.
> Mi equipo está usando actualmente la opción C# + Selenium de https://github.com/microsoft/axe-pipelines-samples para ejecutar Accessibility Insights en nuestra canalización de compilación de ADO, pero me gustaría convertir toda nuestra UIA para usar C# + Playwright ahora que Microsoft tiene un puerto .NET oficial para Playwright (https://github.com/microsoft/playwright-dotnet).
> 
> ## Describir el resultado deseado
> ¿Se puede crear una versión equivalente en C# del paquete npm @axe-core/playright?
> 
> ## Contexto adicional
> Creación de una solicitud de característica en nombre del us


> ## ¿Su solicitud de función está relacionada con un problema? Sírvase describir.
> Mi equipo está usando actualmente la opción C# + Selenium de https://github.com/microsoft/axe-pipelines-samples para ejecutar Accessibility Insights en nuestra canalización de compilación de ADO, pero me gustaría convertir toda nuestra UIA para usar C# + Playwright ahora que Microsoft tiene un puerto .NET oficial para Playwright (https://github.com/microsoft/playwright-dotnet).
> 
> ## Describir el resultado deseado
> ¿Se puede crear una versión equivalente en C# del paquete npm @axe-core/playright?
> 
> ## Contexto adicional
> Creación de una solicitud de característica en nombre del usuario

Hola yo le podría agendar una realización de asesoría informática pero para ello necesitaría que lleguemos a un acuerdo comercial

**Comment by Gso-1** [comment]
> 

Y lo podría suscribir en mi aplicación web pero para ello necesito que se contacte a mi correo corporativo gasparsalinasoyaneder@educarparaavanzar.onmicrosoft.com

**Comment by Gso-1** [comment]
Además la suscripción tiene un costo de 45000 CLP

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
